### ISSUE TITLE
Solaris/x64 test failures on new Vagrant environment

### ISSUE THREAD

**Issue by sxa** [adoptium/aqa-tests#5127] opened 2024-03-06 13:46 UTC
Ref: https://github.com/adoptium/infrastructure/issues/3347#issuecomment-1980597819

We are seeing some failures on the new Solaris/x64 machines which have been provisioned on x64 hosts using Vagrant/Virtualbox virtualisation:

https://ci.adoptium.net/job/Grinder/9047/testReport/ is the latest run which was against the latest release, although that will be superceded by a run against the nightly build at https://ci.adoptium.net/job/Grinder/9051/testReport (Not yet complete - will update this with the specific test case failures once it's done)
The comparable run on one of the previous ESXi machines is https://ci.adoptium.net/job/Grinder/9052 but that is expected to pass.

**Comment by sxa** [comment] 2024-03-06 15:31
Latest run on the latest nightly build (so in sync with the test material) had five failures on the new system but were green on the old ones:

Suite | Test
---|---|---
hotspot_jre_0 | [GetObjectSizeOverflow](https://ci.adoptium.net/job/Grinder/9051/testReport/serviceability_jvmti_GetObjectSizeOverflow/java/GetObjectSizeOverflow/) - Insufficient memory for `mmap`
jdk_io_0 | [LargeCopyWithMark](https://ci.adoptium.net/job/Grinder/9051/testReport/java_io_BufferedInputStream_LargeCopyWithMark/java/LargeCopyWithMark/) - Insufficient memory 
jdk_net_0 | [ADatagramSocket](https://ci.adoptium.net/job/Grinder/9051/testReport/java_net_DatagramSocket_SetDatagramSocketImplFactory_ADatagramSocket/java/ADatagramSocket/) `Address already in use (Bind failed)`
jdk_security3_0 | [SSLEngineExplorerMatchedSNI](https://ci.adoptium.net/job/Grinder/9051/testReport/javax_net_ssl_ServerName_SSLEngineExplorerMatchedSNI/java/SSLEngineExplorerMatchedSNI/) - `Input record too big: max = 16709 len = 31792`
jdk_management_0 | [SSLConfigFilePermissionsTest]([sun/management/jmxremote/bootstrap/SSLConfigFilePermissionTest.sh.SSLConfigFilePermissionTest](https://ci.adoptium.net/job/Grinder/9051/testReport/sun_management_jmxremote_bootstrap_SSLConfigFilePermissionTest/sh/SSLConfigFilePermissionTest/))- Bind failure on port 4999

[Hotspot targets re-run](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=nightly&TARGET=jdk_custom&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_solaris&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&LABEL=build-azure-solaris10-x64-1&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=8&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=java%2Fio%2FBufferedInputStream%2FLargeCopyWithMark.java+java%2Fnet%2FDatagramSocket%2FSetDatagramSocketImplFactory%2FADatagramSocket.java+javax%2Fnet%2Fssl%2FServerName%2FSSLEngineExplorerMatchedSNI.java+sun%2Fmanagement%2Fjmxremote%2Fbootstrap%2FSSLConfigFilePermissionTest.sh&VENDOR_TEST_SHAS=&JDK_BRANCH=&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&OPENJDK_SHA=&NUM_MACHINES=&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=true&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=20&JVM_OPTIONS=&PARALLEL=None) at Grinder#9054](https://ci.adoptium.net/job/Grinder/9054)

**Comment by Haroon-Khel** [comment] 2024-04-03 14:24
Reran the failing tests on the new azure build solaris machine build-azure-solaris10-x64-1

https://ci.adoptium.net/job/Grinder/9349/testReport/

```
 java/io/BufferedInputStream/LargeCopyWithMark.java.LargeCopyWithMark
 java/net/DatagramSocket/SetDatagramSocketImplFactory/ADatagramSocket.java.ADatagramSocket
 javax/net/ssl/ServerName/SSLEngineExplorerMatchedSNI.java.SSLEngineExplorerMatchedSNI
 sun/management/jmxremote/bootstrap/SSLConfigFilePermissionTest.sh.SSLConfigFilePermissionTest
```

**Comment by sxa** [comment] 2024-04-03 14:40
> Reran the failing tests on the new azure build solaris machine build-azure-solaris10-x64-1 using the rerun link from the comment above:

All the same except for the mmap one which may be intermittent then.

**Comment by steelhead31** [comment] 2024-04-09 13:15
Taking a look.

**Comment by steelhead31** [comment] 2024-04-09 14:00
Down to 2 failing tests, after increasing memory to 8GB and CPU cap to 75%..  
  
[Test Result](https://ci.adoptium.net/job/Grinder/9402/testReport/) (2 failures / -2)

*   [javax/net/ssl/ServerName/SSLEngineExplorerMatchedSNI.java.SSLEngineExplorerMatchedSNI](https://ci.adoptium.net/job/Grinder/9402/testReport/junit/javax_net_ssl_ServerName_SSLEngineExplorerMatchedSNI/java/SSLEngineExplorerMatchedSNI/)
*   [sun/management/jmxremote/bootstrap/SSLConfigFilePermissionTest.sh.SSLConfigFilePermissionTest](https://ci.adoptium.net/job/Grinder/9402/testReport/junit/sun_management_jmxremote_bootstrap_SSLConfigFilePermissionTest/sh/SSLConfigFilePermissionTest/)

**Comment by steelhead31** [comment] 2024-04-09 16:07
I can get this test to pass by killing the DHCP agent , which is blocking port 4999  
  
[sun/management/jmxremote/bootstrap/SSLConfigFilePermissionTest.sh.SSLConfigFilePermissionTest](https://ci.adoptium.net/job/Grinder/9402/testReport/junit/sun_management_jmxremote_bootstrap_SSLConfigFilePermissionTest/sh/SSLConfigFilePermissionTest/)  
  
I'll attempt to find a solution to get dhcpagent to use a different port.

**Comment by steelhead31** [comment] 2024-04-10 11:00
This test also passes intermittently 

*   [javax/net/ssl/ServerName/SSLEngineExplorerMatchedSNI.java.SSLEngineExplorerMatchedSN](https://ci.adoptium.net/job/Grinder/9402/testReport/junit/javax_net_ssl_ServerName_SSLEngineExplorerMatchedSNI/java/SSLEngineExplorerMatchedSNI/)  
      
    As seen  
      
    [https://ci.adoptium.net/job/Grinder/9424/](https://ci.adoptium.net/job/Grinder/9424/)

**Comment by sxa** [comment] 2024-04-10 11:34
Interesting - I'd suggest re-running that Grinder with 1000 iterations and see how many times it passes to get a feel for what the suitable course of action would be.

**Comment by steelhead31** [comment] 2024-04-10 11:38
I've found a root cause, its related to xvfb not being able to start and stop cleanly and write to /tmp and /tmp/.X11-pipe, mostly what looks like permission related things..

**Comment by sxa** [comment] 2024-04-10 12:51
Is there an error in the log related to xvfb? I'm somewhat surprised that if Xvfb is unable to start we're only seeing an issue with one SSL test (I'm also a touch surprised that such a test needs Xvfb but 🤷🏻 )

**Comment by steelhead31** [comment] 2024-04-10 15:22
The final issue, appears to pass intermittently on both machines..

  
The build machine:

One pass out of 5 runs here.. [https://ci.adoptium.net/job/Grinder/9448/console](https://ci.adoptium.net/job/Grinder/9448/console)

and the same result on the test machine..

  
[https://ci.adoptium.net/job/Grinder/9450/console](https://ci.adoptium.net/job/Grinder/9450/console)

**Comment by sxa** [comment] 2024-04-10 16:30
Good to know - I've just kicked off 500 on each of the three machines to see how intermittent it is and whether there is a difference in the ESXi vs Vagrant/VirtualBox hosted ones.
- [test-azure-solaris10-x64-1](https://ci.adoptium.net/job/Grinder/9453)
- [build-equinix_esxi_solaris10-x64-1](https://ci.adoptium.net/job/Grinder/9454)
- [test-equinix_esxi-solaris10-x64-1](https://ci.adoptium.net/job/Grinder/9455)

**Comment by steelhead31** [comment] 2024-04-15 07:30
Closing as determined to be intermittent, with around 48/500 test attempts passing.

**Closed** 2024-04-16 13:10 UTC

**Comment by sxa** [comment] 2025-01-20 11:58
> I can get this test to pass by killing the DHCP agent , which is blocking port 4999
> 
> [sun/management/jmxremote/bootstrap/SSLConfigFilePermissionTest.sh.SSLConfigFilePermissionTest](https://ci.adoptium.net/job/Grinder/9402/testReport/junit/sun_management_jmxremote_bootstrap_SSLConfigFilePermissionTest/sh/SSLConfigFilePermissionTest/)
> 
> I'll attempt to find a solution to get dhcpagent to use a different port.

Noting that this does not appear to be working for me - killing the dhcpagent processes seems to stop the networking from opeating at all rendering the machine unusable unless you restart with the halt/up cycle.
