### ISSUE TITLE
JDK8: ppc64le_linux: Test8009761.java fails with: init recursive calls: 38. After deopt 37

### ISSUE THREAD

**Issue by adamfarley** [adoptium/aqa-tests#5221] opened 2024-04-15 12:31 UTC
**Summary**

Test8009761.java fails whenever it is run on a ppc64le_linux Ubuntu 1804 machine, but appears to pass everywhere else.

```
[2023-07-19T16:35:21.776Z] STDOUT:
[2023-07-19T16:35:21.776Z] CompilerOracle: exclude Test8009761.m2
[2023-07-19T16:35:21.776Z] Failed: init recursive calls: 38. After deopt 37
```

Example: https://trss.adoptium.net/output/test?id=64b83aef17052c671586e467
Deep History: https://trss.adoptium.net/deepHistory?testId=6615e317879917006efa06ea

**Details**

From 2023-07-19 (possibly earlier) to now, Test8009761 has always failed with this error when it is run on one of our ppc64le_linux Ubuntu 1804 machines, such as test-osuosl-ubuntu1804-ppc64le-2.

OS' that this test is proved to pass on include:
- All Debian versions
- Ubuntu 1604
- Ubuntu 2004 and up

As far as I can tell, Test8009761 has been failing for many years, but was ignored/excluded due to an issue affecting many compiler tests ([link](https://github.com/adoptium/aqa-tests/issues/3059)) that affected it on all ppcle machines.

It seems this issue was resolved [here](https://bugs.openjdk.org/browse/JDK-8067941), and then unexcluded [here](https://github.com/adoptium/aqa-tests/pull/4317) on 2023-02-07. Records between there and 2023-07-19 are not present, so I don't think we can be sure when the "init recursive" problem started, as the stack issue may have concealed it by causing (a) failure prior to the recursive issue, or (b) causing so many failures on the non-ubuntu-1804 machines that the recursive issues were drowned out.

Also, here are some examples of past failures of this test, and how they were fixed:
- https://bugs.openjdk.org/browse/JDK-8012936
- https://bugs.openjdk.org/browse/JDK-8015033
- https://bugs.openjdk.org/browse/JDK-8017750

I'm not currently seeing an unresolved upstream bug that looks identical to this issue.

**Machine stats**

In case this was not an OS issue, but rather a throughput issue, I pulled out some stats for the failing/passing machines. I don't see a pattern, sadly. See below for the numbers, in case someone has another theory.

| Data | test-osuosl-ubuntu1804-ppc64le-2 (fail) | 	test-osuosl-ubuntu2004-ppc64le-1 | 	test-skytap-ubuntu2004-ppc64le-1 | 	test-docker-debian11-ppc64le-1 | 	test-osuosl-ubuntu1604-ppc64le-1 | 
|-|-|-|-|-|-|
| Free Physical Memory Size | 	4750508032 | 	278855680 | 	387776512 | 	4056809472 | 	5065408512 | 
| Free space (bytes) | 	30003261440 | 	15444140032 | 	409540165632 | 	309474676736 | 	55724167168 | 
| Total Physical Memory Size | 	8556511232 | 	4252565504 | 	8488419328 | 	6442450944 | 	8559984640 | 
| Total space (bytes) | 	84449624064 | 	41551020032 | 	422622445568 | 	422548791296 | 	83203571712 | 
| Usable space (bytes) | 	26508455936 | 	15427362816 | 	388065382400 | 	287999893504 | 	55707389952 | 
| cpuCores | 	4 | 	2 | 	32 | 	32 | 	4 |

**Comment by adamfarley** [comment] 2024-04-15 13:02
Here are a couple of grinders for this test, each one a 100x grinder of this specific unit test.

- Ubuntu 2004: 
- Ubuntu 1804: 

Also, for the last 12 runs of this test target, here are the pass/fails:
- Pass
test-docker-debian11-ppc64le-1
test-docker-debian11-ppc64le-3 x2
test-docker-ubuntu2204-ppc64le-1
test-docker-ubuntu2204-ppc64le-2
test-osuosl-ubuntu2004-ppc64le-1
test-osuosl-ubuntu1604-ppc64le-1 x2
test-skytap-ubuntu2004-ppc64le-1

- Fail
test-docker-ubuntu1804-ppc64le-1
test-osuosl-ubuntu1804-ppc64le-2 x2

**Comment by adamfarley** [comment] 2024-04-15 15:42
Ok, the Grinders were conclusive.

100/100 of the tests on test-osuosl-ubuntu2004-ppc64le-1 passed.
100/100 of the tests on test-osuosl-ubuntu1804-ppc64le-1 failed with exactly this issue.

**Comment by jiekang** [comment] 2024-04-15 16:21
This test was rewritten in JDK 9 and allows the call count to be off by one. That might allow us to pass this test on this one special platform. 

For our own purposes I wouldn't consider this test failure a blocker so there wouldn't be any priority action to resolve it.The rewrite was 10 years ago now... Maybe it would be nice to backport the adjustment to the assert 8?


JDK 8:
https://github.com/openjdk/jdk8u-dev/blob/cde8aca6cb0fae77b9300b9d65d094a4f74e4d53/hotspot/test/compiler/8009761/Test8009761.java#L249

Head:
https://github.com/openjdk/jdk/blob/140f56718bbbfc31bb0c39255c68568fad285a1f/test/hotspot/jtreg/compiler/uncommontrap/Test8009761.java#L284
Fix was to allow the count to be off by one, lol..

**Comment by adamfarley** [comment] 2024-04-16 14:19
Master exclusion: https://github.com/adoptium/aqa-tests/pull/5228
Will be cherry picked and merged into latest release branch once approved+merged.

**Comment by sendaoYan** [comment] 2024-04-21 05:46
Hi,
  How can I reproduce this failure, because I do not a ppc64le_linux machine.

**Comment by smlambert** [comment] 2024-04-21 11:36
Hi @sendaoYan - look for an invitation to a test-triage team.  Once you accept the invitation, you can try running these Grinder jobs on Jenkins:

- [Grinder job on 1804 node](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=jdk_custom&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk8_hs_extended.openjdk_ppc64le_linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=5&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64le_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&LABEL=test-osuosl-ubuntu1804-ppc64le-1&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fci.adoptium.net%2Fjob%2Fbuild-scripts%2Fjob%2Frelease-openjdk8-pipeline%2F46%2Fartifact%2Ftarget%2Flinux%2Fppc64le%2Ftemurin%2FOpenJDK8U-jdk_ppc64le_linux_hotspot_8u412b06.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=v1.0.1-release&LIGHT_WEIGHT_CHECKOUT=false&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=8&ITERATIONS=100&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk8u&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=%2F..%2F..%2Fhotspot%2Ftest%2Fcompiler%2F8009761%2FTest8009761.java&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk8u412-b06_adopt&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=171&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&OPENJDK_SHA=&NUM_MACHINES=&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=true&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=25&JVM_OPTIONS=&PARALLEL=None) - runs on test-osuosl-ubuntu1804-ppc64le-1
- [Grinder job on 2004 node](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=jdk_custom&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk8_hs_extended.openjdk_ppc64le_linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=5&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64le_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&LABEL=test-osuosl-ubuntu2004-ppc64le-1&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fci.adoptium.net%2Fjob%2Fbuild-scripts%2Fjob%2Frelease-openjdk8-pipeline%2F46%2Fartifact%2Ftarget%2Flinux%2Fppc64le%2Ftemurin%2FOpenJDK8U-jdk_ppc64le_linux_hotspot_8u412b06.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=v1.0.1-release&LIGHT_WEIGHT_CHECKOUT=false&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=8&ITERATIONS=100&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk8u&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=%2F..%2F..%2Fhotspot%2Ftest%2Fcompiler%2F8009761%2FTest8009761.java&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk8u412-b06_adopt&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=171&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&OPENJDK_SHA=&NUM_MACHINES=&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=true&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=25&JVM_OPTIONS=&PARALLEL=None) - runs on test-osuosl-ubuntu2004-ppc64le-1

If you need direct access to either test machine, you would raise an [infrastructure issue](https://github.com/adoptium/infrastructure/issues/new?assignees=sxa&labels=Temp+Infra+Access&projects=&template=machineaccess.md&title=Access+request+for+%3Cyour+username%3E) to request it.

**Comment by sendaoYan** [comment] 2024-04-22 03:17
> Hi @sendaoYan - look for an invitation to a test-triage team. Once you accept the invitation, you can try running these Grinder jobs on Jenkins:
> 
> * [Grinder job on 1804 node](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=jdk_custom&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk8_hs_extended.openjdk_ppc64le_linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=5&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64le_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&LABEL=test-osuosl-ubuntu1804-ppc64le-1&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fci.adoptium.net%2Fjob%2Fbuild-scripts%2Fjob%2Frelease-openjdk8-pipeline%2F46%2Fartifact%2Ftarget%2Flinux%2Fppc64le%2Ftemurin%2FOpenJDK8U-jdk_ppc64le_linux_hotspot_8u412b06.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=v1.0.1-release&LIGHT_WEIGHT_CHECKOUT=false&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=8&ITERATIONS=100&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk8u&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=%2F..%2F..%2Fhotspot%2Ftest%2Fcompiler%2F8009761%2FTest8009761.java&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk8u412-b06_adopt&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=171&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&OPENJDK_SHA=&NUM_MACHINES=&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=true&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=25&JVM_OPTIONS=&PARALLEL=None) - runs on test-osuosl-ubuntu1804-ppc64le-1
> * [Grinder job on 2004 node](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=jdk_custom&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk8_hs_extended.openjdk_ppc64le_linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=5&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=ppc64le_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&LABEL=test-osuosl-ubuntu2004-ppc64le-1&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fci.adoptium.net%2Fjob%2Fbuild-scripts%2Fjob%2Frelease-openjdk8-pipeline%2F46%2Fartifact%2Ftarget%2Flinux%2Fppc64le%2Ftemurin%2FOpenJDK8U-jdk_ppc64le_linux_hotspot_8u412b06.tar.gz&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=v1.0.1-release&LIGHT_WEIGHT_CHECKOUT=false&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=8&ITERATIONS=100&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk8u&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=%2F..%2F..%2Fhotspot%2Ftest%2Fcompiler%2F8009761%2FTest8009761.java&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk8u412-b06_adopt&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=171&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&OPENJDK_SHA=&NUM_MACHINES=&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=true&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=25&JVM_OPTIONS=&PARALLEL=None) - runs on test-osuosl-ubuntu2004-ppc64le-1
> 
> If you need direct access to either test machine, you would raise an [infrastructure issue](https://github.com/adoptium/infrastructure/issues/new?assignees=sxa&labels=Temp+Infra+Access&projects=&template=machineaccess.md&title=Access+request+for+%3Cyour+username%3E) to request it.

Thanks.

**Comment by adamfarley** [comment] 2024-04-23 13:03
Upstream bug raised here: https://bugs.openjdk.org/browse/JDK-8330973
Upstream PR raised here: https://github.com/openjdk/jdk8u-dev/pull/487

**Comment by adamfarley** [comment] 2024-04-24 08:59
Severin has asked for a backport of the full JDK9 fix, rather than the minimal version, so I'm checking the backport to make sure it's clean.

**Comment by adamfarley** [comment] 2024-05-09 15:35
Looking into the creation of the backport PR now.

Commit generated [here](https://github.com/openjdk/jdk8u-dev/commit/7a269c7d89c6c4781f194548dc723818a456411d). Testing underway. Links to follow.

**Comment by adamfarley** [comment] 2024-07-10 09:21
Resuming this task. Here's a grinder rerun: https://ci.adoptium.net/job/Grinder/10553/

**Comment by adamfarley** [comment] 2024-08-21 09:51
Update: The upstream PR has been merged into jdk8u dev. Will unexclude this test once the change gets merged into jdk8u.

**Comment by jiekang** [comment] 2024-10-17 16:58
@adamfarley Looks like this was merged in for this October CPU (2024-10) so you can revisit the exclusion now

**Comment by adamfarley** [comment] 2024-11-04 16:04
[Test passed](https://ci.adoptium.net/job/Grinder/11285/console). PR raised here: https://github.com/adoptium/aqa-tests/pull/5732

**Closed** 2024-11-04 16:16 UTC
