### ISSUE TITLE
renaissance test Java 11 Linux x86-64 - java.net.UnknownHostException: test-packet-ubuntu1604-x64-2.adoptopenjdk.net: Name or service not known (only fails on that host)

### ISSUE THREAD

**Issue by karianna** [adoptium/aqa-tests#3236] opened 2022-01-19 13:47 UTC
https://trss.adoptium.net/output/test?id=61e78b73a7df1a2924021901

[2022-01-18T22:26:05.656Z] Running test renaissance-als_0 ...
[2022-01-18T22:26:05.656Z] ===============================================
[2022-01-18T22:26:05.656Z] renaissance-als_0 Start Time: Tue Jan 18 22:26:04 2022 Epoch Time (ms): 1642544764616
[2022-01-18T22:26:05.656Z] Nothing to be done for setup.
[2022-01-18T22:26:05.656Z] variation: NoOptions
[2022-01-18T22:26:05.656Z] JVM_OPTIONS:  
[2022-01-18T22:26:05.656Z] { itercnt=1; \
[2022-01-18T22:26:05.656Z] mkdir -p "/home/jenkins/workspace/Test_openjdk11_hs_extended.perf_x86-64_linux/aqa-tests/TKG/../TKG/output_16425446819586/renaissance-als_0"; \
[2022-01-18T22:26:05.656Z] cd "/home/jenkins/workspace/Test_openjdk11_hs_extended.perf_x86-64_linux/aqa-tests/TKG/../TKG/output_16425446819586/renaissance-als_0"; \
[2022-01-18T22:26:05.656Z] "/home/jenkins/workspace/Test_openjdk11_hs_extended.perf_x86-64_linux/openjdkbinary/j2sdk-image/bin/java"  -jar "/home/jenkins/workspace/Test_openjdk11_hs_extended.perf_x86-64_linux/aqa-tests/TKG/../../jvmtest/perf/renaissance/renaissance.jar" --json ""/home/jenkins/workspace/Test_openjdk11_hs_extended.perf_x86-64_linux/aqa-tests/TKG/../TKG/output_16425446819586/renaissance-als_0"/als.json" als; \
[2022-01-18T22:26:05.656Z] 	if [ $? -eq 0 ] ; then echo ""; echo "renaissance-als_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Test_openjdk11_hs_extended.perf_x86-64_linux/aqa-tests/TKG/..; rm -f -r "/home/jenkins/workspace/Test_openjdk11_hs_extended.perf_x86-64_linux/aqa-tests/TKG/../TKG/output_16425446819586/renaissance-als_0"; else echo ""; echo "renaissance-als_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Test_openjdk11_hs_extended.perf_x86-64_linux/aqa-tests/TKG/../TKG/output_16425446819586/TestTargetResult";
[2022-01-18T22:26:11.357Z] Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2022-01-18T22:26:11.357Z] 22/01/18 22:26:10 INFO SparkContext: Running Spark version 2.0.0
[2022-01-18T22:26:11.357Z] WARNING: An illegal reflective access operation has occurred
[2022-01-18T22:26:11.357Z] WARNING: Illegal reflective access by org.apache.hadoop.security.authentication.util.KerberosUtil (file:/home/jenkins/workspace/Test_openjdk11_hs_extended.perf_x86-64_linux/aqa-tests/TKG/output_16425446819586/renaissance-als_0/./tmp-jars-9910105100278028189/cp-11173651356767998090.jar) to method sun.security.krb5.Config.getInstance()
[2022-01-18T22:26:11.357Z] WARNING: Please consider reporting this to the maintainers of org.apache.hadoop.security.authentication.util.KerberosUtil
[2022-01-18T22:26:11.357Z] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2022-01-18T22:26:11.357Z] WARNING: All illegal access operations will be denied in a future release
[2022-01-18T22:26:11.357Z] 22/01/18 22:26:11 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2022-01-18T22:26:11.357Z] 22/01/18 22:26:11 WARN SparkConf: In Spark 1.0 and later spark.local.dir will be overridden by the value set by the cluster manager (via SPARK_LOCAL_DIRS in mesos/standalone and LOCAL_DIRS in YARN).
[2022-01-18T22:26:11.357Z] 22/01/18 22:26:11 ERROR SparkContext: Error initializing SparkContext.
[2022-01-18T22:26:11.357Z] java.net.UnknownHostException: test-packet-ubuntu1604-x64-2.adoptopenjdk.net: test-packet-ubuntu1604-x64-2.adoptopenjdk.net: Name or service not known
[2022-01-18T22:26:11.357Z] 	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1646)
[2022-01-18T22:26:11.357Z] 	at org.apache.spark.util.Utils$.findLocalInetAddress(Utils.scala:846)
[2022-01-18T22:26:11.357Z] 	at org.apache.spark.util.Utils$.org$apache$spark$util$Utils$$localIpAddress$lzycompute(Utils.scala:839)
[2022-01-18T22:26:11.357Z] 	at org.apache.spark.util.Utils$.org$apache$spark$util$Utils$$localIpAddress(Utils.scala:839)
[2022-01-18T22:26:11.357Z] 	at org.apache.spark.util.Utils$$anonfun$localHostName$1.apply(Utils.scala:896)
[2022-01-18T22:26:11.357Z] 	at org.apache.spark.util.Utils$$anonfun$localHostName$1.apply(Utils.scala:896)
[2022-01-18T22:26:11.357Z] 	at scala.Option.getOrElse(Option.scala:121)
[2022-01-18T22:26:11.357Z] 	at org.apache.spark.util.Utils$.localHostName(Utils.scala:896)
[2022-01-18T22:26:11.357Z] 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:388)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.apache.spark.Als.setUpSpark(Als.scala:74)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.apache.spark.Als.setUpBeforeAll(Als.scala:80)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.RenaissanceBenchmark.runBenchmark(RenaissanceBenchmark.java:74)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.RenaissanceSuite$.$anonfun$main$2(renaissance-suite.scala:308)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.RenaissanceSuite$.$anonfun$main$2$adapted(renaissance-suite.scala:306)
[2022-01-18T22:26:11.357Z] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2022-01-18T22:26:11.357Z] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2022-01-18T22:26:11.357Z] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.RenaissanceSuite$.main(renaissance-suite.scala:306)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.RenaissanceSuite.main(renaissance-suite.scala)
[2022-01-18T22:26:11.357Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-01-18T22:26:11.357Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-01-18T22:26:11.357Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-01-18T22:26:11.357Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.Launcher.main(Launcher.java:18)
[2022-01-18T22:26:11.357Z] Caused by: java.net.UnknownHostException: test-packet-ubuntu1604-x64-2.adoptopenjdk.net: Name or service not known
[2022-01-18T22:26:11.357Z] 	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
[2022-01-18T22:26:11.357Z] 	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
[2022-01-18T22:26:11.357Z] 	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
[2022-01-18T22:26:11.357Z] 	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
[2022-01-18T22:26:11.357Z] 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2022-01-18T22:26:11.357Z] 	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1641)
[2022-01-18T22:26:11.357Z] 	... 23 more
[2022-01-18T22:26:11.357Z] 22/01/18 22:26:11 INFO SparkContext: Successfully stopped SparkContext
[2022-01-18T22:26:11.357Z] Error during tear-down: null
[2022-01-18T22:26:11.357Z] java.lang.NullPointerException
[2022-01-18T22:26:11.357Z] 	at org.renaissance.apache.spark.Als.tearDownAfterAll(Als.scala:87)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.RenaissanceBenchmark.runBenchmark(RenaissanceBenchmark.java:97)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.RenaissanceSuite$.$anonfun$main$2(renaissance-suite.scala:308)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.RenaissanceSuite$.$anonfun$main$2$adapted(renaissance-suite.scala:306)
[2022-01-18T22:26:11.357Z] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2022-01-18T22:26:11.357Z] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2022-01-18T22:26:11.357Z] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.RenaissanceSuite$.main(renaissance-suite.scala:306)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.RenaissanceSuite.main(renaissance-suite.scala)
[2022-01-18T22:26:11.357Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-01-18T22:26:11.357Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-01-18T22:26:11.357Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-01-18T22:26:11.357Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.Launcher.main(Launcher.java:18)
[2022-01-18T22:26:11.357Z] Exception occurred in org.renaissance.apache.spark.Als@530a8454: test-packet-ubuntu1604-x64-2.adoptopenjdk.net: test-packet-ubuntu1604-x64-2.adoptopenjdk.net: Name or service not known
[2022-01-18T22:26:11.357Z] java.net.UnknownHostException: test-packet-ubuntu1604-x64-2.adoptopenjdk.net: test-packet-ubuntu1604-x64-2.adoptopenjdk.net: Name or service not known
[2022-01-18T22:26:11.357Z] 	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1646)
[2022-01-18T22:26:11.357Z] 	at org.apache.spark.util.Utils$.findLocalInetAddress(Utils.scala:846)
[2022-01-18T22:26:11.357Z] 	at org.apache.spark.util.Utils$.org$apache$spark$util$Utils$$localIpAddress$lzycompute(Utils.scala:839)
[2022-01-18T22:26:11.357Z] 	at org.apache.spark.util.Utils$.org$apache$spark$util$Utils$$localIpAddress(Utils.scala:839)
[2022-01-18T22:26:11.357Z] 	at org.apache.spark.util.Utils$$anonfun$localHostName$1.apply(Utils.scala:896)
[2022-01-18T22:26:11.357Z] 	at org.apache.spark.util.Utils$$anonfun$localHostName$1.apply(Utils.scala:896)
[2022-01-18T22:26:11.357Z] 	at scala.Option.getOrElse(Option.scala:121)
[2022-01-18T22:26:11.357Z] 	at org.apache.spark.util.Utils$.localHostName(Utils.scala:896)
[2022-01-18T22:26:11.357Z] 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:388)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.apache.spark.Als.setUpSpark(Als.scala:74)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.apache.spark.Als.setUpBeforeAll(Als.scala:80)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.RenaissanceBenchmark.runBenchmark(RenaissanceBenchmark.java:74)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.RenaissanceSuite$.$anonfun$main$2(renaissance-suite.scala:308)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.RenaissanceSuite$.$anonfun$main$2$adapted(renaissance-suite.scala:306)
[2022-01-18T22:26:11.357Z] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2022-01-18T22:26:11.357Z] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2022-01-18T22:26:11.357Z] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.RenaissanceSuite$.main(renaissance-suite.scala:306)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.RenaissanceSuite.main(renaissance-suite.scala)
[2022-01-18T22:26:11.357Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-01-18T22:26:11.357Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-01-18T22:26:11.357Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-01-18T22:26:11.357Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-01-18T22:26:11.357Z] 	at org.renaissance.Launcher.main(Launcher.java:18)
[2022-01-18T22:26:11.357Z] Caused by: java.net.UnknownHostException: test-packet-ubuntu1604-x64-2.adoptopenjdk.net: Name or service not known
[2022-01-18T22:26:11.357Z] 	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
[2022-01-18T22:26:11.357Z] 	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
[2022-01-18T22:26:11.357Z] 	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
[2022-01-18T22:26:11.357Z] 	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
[2022-01-18T22:26:11.357Z] 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2022-01-18T22:26:11.357Z] 	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1641)
[2022-01-18T22:26:11.357Z] 	... 23 more
[2022-01-18T22:26:11.357Z] The following benchmarks failed: als
[2022-01-18T22:26:11.661Z] 
[2022-01-18T22:26:11.662Z] renaissance-als_0_FAILED
[2022-01-18T22:26:11.662Z] 
[2022-01-18T22:26:11.662Z] Nothing to be done for teardown.
[2022-01-18T22:26:11.662Z] renaissance-als_0 Finish Time: Tue Jan 18 22:26:11 2022 Epoch Time (ms): 1642544771418

**Comment by smlambert** [comment] 2022-01-25 21:51
Closing this as the issue is now tracked under https://github.com/adoptium/infrastructure/issues/2452

**Closed by smlambert** 2022-01-25 21:51 UTC
Labels: linux, release triage
