### ISSUE TITLE
CryptoTests doesn't show junit test report 

### ISSUE THREAD

**Issue by annaibm** [adoptium/aqa-tests#5206] opened 2024-04-09 12:45 UTC
During the execution of CryptoTests in Grinder, an error was encountered in `cryptotest/CryptoTest.java`, but the output provided insufficient detail to diagnose the cause of the failure. 
This issue occurred during a Jenkins pipeline run, impacting our ability to efficiently troubleshoot and find the reason for the test failure.

Actual Behaviour: 
The test execution resulted in an error for `cryptotest/CryptoTest.java` without providing detailed error information or stack trace. 
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/39513/consoleFull
```
Passed: cryptotest/tests/XMLSignatureFactoryTests.java
08:48:19  Error:  cryptotest/CryptoTest.java
08:48:19  Test results: passed: 31; error: 1
08:48:19  Report written to /home/jenkins/workspace/Grinder/aqa-tests/functional/security/Crypto/CryptoTest/test.1712405766/jdk/JTreport/html/report.html
08:48:19  Results written to /home/jenkins/workspace/Grinder/aqa-tests/functional/security/Crypto/CryptoTest/test.1712405766/jdk/JTwork
08:48:19  Error: Some tests failed or other problems occurred.
08:48:19  ~/workspace/Grinder/aqa-tests/TKG/output_1712405765144/CryptoTests_0
08:48:19  renamed '/home/jenkins/workspace/Grinder/aqa-tests/functional/security/Crypto/CryptoTest/test.1712405766.tar.gz' -> './test.1712405766.tar.gz'
08:48:19  -----------------------------------
08:48:19  CryptoTests_0_FAILED
08:48:19  -----------------------------------
```

### Steps to Reproduce
1. Trigger the Grinder test through Jenkins pipeline with BUILD_LIST: `functional` and TARGET: `CryptoTests_0`
2. Observe the test execution output, particularly for `cryptotest/CryptoTest.java`.

**Comment by llxia** [comment] 2024-04-11 19:15
In AQA pipeline, it consumes the *.jtf files under `work` and `junit` folder. However, we are not able to see any junit output. Any idea where the jtr.xml is generated in Crypto tests?

Also, only files under `$(REPORTDIR)` will be archived. Crypto tests run https://github.com/rh-openjdk/CryptoTest/blob/master/run.sh which redirects the output outside of `$(REPORTDIR)`, which results the output not been archived. That is the reason that I am suggesting to redirect test output into $(REPORTDIR).

Note: by default workspace will be cleaned up after the test run, so the pipeline needs to archive all the necessary logs for triaging and debugging purpose.

**Comment by judovana** [comment] 2024-04-12 09:08
>  *.jtf 

You mean jtr, right?


I originally have the (reportdir)  set, but I was recommended to not use it, but use CWD instead. And indeed, it was working. 
See this grinder job: https://ci.adoptium.net/view/Test_grinder/job/Grinder/9478/
In artifacts, there is: `functional_security_Crypto_test_output.tar.gz`  inside is  `/./aqa-tests/TKG/output_17129097228343/CryptoTests_0/test.1712909723/jdk/JTwork/cryptotest/`  and there is `jtr/xml` for each test. Which is waht jtreg-plugin can consume. And it is what the log is pointing out `XML output  to /home/jenkins/workspace/Grinder/aqa-tests/functional/security/Crypto/CryptoTest/test.1712909723/jdk/JTwork`

As I saw those results in the grinder I thought it is done.

So you suggests, that current approach is incomplete  and you want:
 - copy  all `jtr.xml` files from `test.1....` to `$(REPORTDIR)`
   -   and from there, junit plugin will consume it out of box
Which I would extend also for
 - copy  `test.1.....tar.gz` to `$(REPORTDIR)`
   -    so I can continue reading the tarball with jtreg-plugin

This change is applicable to ssl-tests, cryptotoests and churn.

**Comment by llxia** [comment] 2024-04-12 18:48
- for jtr files, https://github.com/rh-openjdk/CryptoTest/blob/master/run.sh#L137 ` -w:test.${TIME}/jdk/JTwork -r:test.${TIME}/jdk/JTreport \`. 
   - We can update the pipeline code to include `JTwork` folder. PR will be created shortly.
- for tar.gz, it is archived via AQA pipeline as it is output to the current dir (.), which is under $(REPORTDIR). I do not know what went wrong with https://github.com/adoptium/aqa-tests/issues/5206#issuecomment-2045314595 as there is no console output or tar.gz. I hope this is a one-off. If not, we need more output from CryptoTest.

**Comment by smlambert** [comment] 2024-04-14 20:26
Another thing to look at is what is different about the location and behaviour of the test results from rh-openjdk versus those from the openjdk project, and align them with what is happening in the openjdk project (especially for jtreg-buffer tests, those tests which intend to be upstreamed to that project).  If it is because upstream OpenJDK is putting them into a directory named work and rh-openjdk is putting into a dir called JTwork, perhaps the rh-openjdk test code wants to align with the behaviour of openjdk and put into work, instead of JTwork?  Also fine with the update in #5206, but it seems like there is extra behaviour being done in test material from rh-openjdk that is 'unexpected'.  For example, is it actively putting its own results into a tar.gz file, instead of leaving that to the Jenkins script?

**Comment by judovana** [comment] 2024-04-15 07:19
The `"${JAVA_HOME}/bin/java" -jar "$JTREG_JAR" -v1 -a -ignore:quiet ` is hardcoded in all our launchers.
I  think I do not have objections to align it with your.  In worst  I will create backward symlinsk for myself.

**Comment by judovana** [comment] 2024-04-15 09:06
> ...Also fine with the update in #5206, but it seems like there is extra behaviour being done in test material from rh-openjdk ... 
s/5206/https://github.com/adoptium/aqa-tests/pull/5218 ?

**Comment by llxia** [comment] 2024-04-15 15:08
It is not only `JTwrork` dir issue in rh-openjdk/CryptoTest repo. https://github.com/rh-openjdk/CryptoTest/blob/master/run.sh also changed the work dir from `$(REPORTDIR)` to resource dir `/home/jenkins/workspace/Grinder/aqa-tests/functional/security/Crypto/CryptoTest/`. See the output below:


- `04:15:23  cd "/home/jenkins/workspace/Grinder/aqa-tests/TKG/../TKG/output_17129097228343/CryptoTests_0"; \` ==> $(REPORTDIR)
- `04:15:25  XML output  to /home/jenkins/workspace/Grinder/aqa-tests/functional/security/Crypto/CryptoTest/test.1712909723/jdk/JTwork` ==> output dir got changed
...
04:28:01  Report written to /home/jenkins/workspace/Grinder/aqa-tests/functional/security/Crypto/CryptoTest/test.1712909723/jdk/JTreport/html/report.html
04:28:01  Results written to /home/jenkins/workspace/Grinder/aqa-tests/functional/security/Crypto/CryptoTest/test.1712909723/jdk/JTwork
04:28:01  ~/workspace/Grinder/aqa-tests/TKG/output_17129097228343/CryptoTests_0
04:28:01  renamed '/home/jenkins/workspace/Grinder/aqa-tests/functional/security/Crypto/CryptoTest/test.1712909723.tar.gz' -> './test.1712909723.tar.gz' ==> tar.gz got archived in AQA pipeline because it is moved back to $(REPORTDIR)

see https://ci.adoptium.net/view/Test_grinder/job/Grinder/9478/console

PR https://github.com/adoptium/aqa-tests/pull/5218 is created assuming that we do not want to change code in rh-openjdk/CryptoTest repo. If we would like to fix this in rh-openjdk/CryptoTest repo (preferred), then 
- it should not change the work dir, the current dir should be used
- do not need zip test output. It will be handled by AQA test pipeline
- rename `JTwork` to `work` and align with openjdk

Related code:
https://github.com/rh-openjdk/CryptoTest/blob/master/run.sh#L18
https://github.com/rh-openjdk/CryptoTest/blob/master/run.sh#L135
https://github.com/rh-openjdk/CryptoTest/blob/master/run.sh#L145

**Comment by judovana** [comment] 2024-04-16 07:01
Hi!

> 
>     * it should not change the work dir, the current dir should be used

Why? It change dir, do the work, and then copy results to original location. 
If also jtwork (future work) dir should be copied, then why not.

> 
>     * do not need zip test output. It will be handled by AQA test pipeline

That is mandatory step. I relay on jtreg plugin, and I really do not want to be tarring it else where.
> 
>     * rename `JTwork` to `work` and align with openjdk

I guess that is the best thing to do.

**Comment by judovana** [comment] 2024-04-17 13:51
https://github.com/rh-openjdk/CryptoTest/pull/67
- renamed jtwork-> work.  
+ few other tings I started before CPU but did not merged... sorry.

* It sitll tar the output (and will continue to do
* is still changin g the dir.. I can not see why it shoudl not
* `work and report` are correcty copied togehter with tarball.

**Comment by judovana** [comment] 2024-04-17 14:23
run.sh is what any 3rd party user is using. run.sh is what  GH actions are using, run.sh is what our parts of infra which are not yet i adoptium are using. I do not want to maintian 4 launchers, I want to maintain one properly. To miss taht in original PR was error.

**Comment by smlambert** [comment] 2024-04-17 14:26
There is less to maintain by stripping out the run.sh file from the command in the playlist and returning to calling the java test code directly.

**Comment by judovana** [comment] 2024-04-17 14:34
> To add a maintainability point, we need to ensure compatibility across multiple platforms, including z/OS. This means the shell script has to use the cmd that can run on all platforms. And it must undergo comprehensive testing before integration. Generally, it's risky to execute a shell script from another repository where we lack visibility.
> 
> currently, archiving on zos failed with `name too long`
> 
> ```
> 01:02:53.872  FAILED: cryptotest/CryptoTest.java
> 01:02:53.872  Test results: passed: 26; failed: 5; error: 1
> 01:02:53.872  Error: Some tests failed or other problems occurred.
> 01:02:53.872  Report written to /home/jenkins/workspace/Test_openjdk11_ibm_extended.functional_s390x_zos_Nightly_testList_0/aqa-tests/functional/security/Crypto/CryptoTest/test.%s/jdk/JTreport/html/report.html
> 01:02:53.872  Results written to /home/jenkins/workspace/Test_openjdk11_ibm_extended.functional_s390x_zos_Nightly_testList_0/aqa-tests/functional/security/Crypto/CryptoTest/test.%s/jdk/JTwork
> 01:02:53.872  FSUM7218 tar: test.%s/jdk/JTwork/classes/cryptotest/tests/cryptotest/tests/SaslServerFactoryTests$PrivilegedSubjectAction.class: name too long
> 01:02:53.872  -----------------------------------
> 01:02:53.872  CryptoTests_0_FAILED
> 01:02:53.872  -----------------------------------
> ```

But that is ok. I will gladly help tune up the `run.sh` to suit you.  Then it is beneficial also to CryptoTests and users of z/OS may use them as standalon product.

The `readlink -f` issue was fixable

**Comment by judovana** [comment] 2024-04-17 14:52
> > > 01:02:53.872  FSUM7218 tar: test.%s/jdk/JTwork/classes/cryptotest/tests/cryptotest/tests/SaslServerFactoryTests$PrivilegedSubjectAction.class: name too long
> 
> Gosh. ok.

https://github.com/rh-openjdk/CryptoTest/pull/67/commits/654477a20e52f47becd80002137bdb2fac714cb6

**Comment by smlambert** [comment] 2024-04-17 15:09
> There is less to maintain by stripping out the run.sh file from the command in the playlist and returning to calling the java test code directly.

Chatted with @judovana on this topic.  

We will consider that rh-openjdk is a suite of test material (CryptoTest, ssl-tests, TestHeadlessComponents, churn, jtreg-buffer, MSITests, etc) separate from openjdk (even though jtreg-buffer is intended to be upstreamed to openjdk), that will standardize their runners to be named in a predictable way, take same options (or behave gracefully when provided options that not applicable), etc.

As we build out AQAvit test suite (for use by so many vendors), we want to select test suites that are designed with consumability and automation in mind (which is actually why I had assumed the choice of jtreg was made as the underlying framework for the rh-openjdk tests, not actually expecting to have to manage a different launcher that takes different options for each suite.  So we can/should go through the exercise of sanitizing/documenting the set.

At present, of the suites we are trying to integrate into AQAvit:
| rh-openjdk suite name | launcher | supported options |
| --- | --- | --- | 
| CryptoTest | /run.sh |  TBD | 
| ssl-tests | /run.sh | TBD | 
| jtreg-buffer | /run.sh | TBD | 
| churn | /run.sh | TBD | 
| TestHeadlessComponents | /testHeadlessComponents.sh   | TBD | 
| MSITests | /wrapper/run-tps-win-vagrant.sh  | TBD |

**Comment by judovana** [comment] 2024-04-17 15:28
Thanx! yy, I will definitely do (with @rcap and @jandrlik )  my best to adjsut those runners to fit to aqa-vit and unify them as much as possible.
One small addition info:  - CryptoTest, ssl-tests and jtreg-buffer are jtreg based suites. churn, TestHeadlessComponents, and MSITests are not. For Churn and TestHeadlessComponents it should be ok  to make artificial alignments. With MSITests hard to say,  Afaik it is not in aqavit yet. And is ... quite different then the otjers.

**Comment by judovana** [comment] 2024-04-18 17:36
> CryptoTest 	/run.sh 	TBD

adapted to use work dir + many small tweeks

> ssl-tests 	/run.sh 	TBD

adapted to use work dir + many small tweeks
> jtreg-buffer 	/run.sh 	TBD

adapted to use work dir + many small tweeks

Also some internal suites which have simialr structure adjusted.

> churn 	/run.sh 	TBD
> TestHeadlessComponents 	/testHeadlessComponents.sh 	TBD
> MSITests 	/wrapper/run-tps-win-vagrant.sh 	TBD

@llxia  is the work dir change visible somewhere, and is junit processing it correctly?

Once confirmed, will elaborate  on churn and TestHeadlessComponents.  Here I will fix wget x curl and  readlink -f and will try to figiure out what to do with work. As there is no such concept.

**Comment by llxia** [comment] 2024-04-18 17:51
I talked with @smlambert , we will create a separate target for CryptoTest to trigger tests directly using jtreg, say `CryptoTests_jtreg`. `CryptoTests` will remain running with run.sh in CryptoTest repo. Once run.sh at CryptoTest is fully prepared for execution on all platforms, we can consolidate it into one file in the future.

This is to avoid situations like https://github.com/eclipse-openj9/openj9/issues/19164#issuecomment-2064179534, where we lack access to the machine or the env.

**Comment by judovana** [comment] 2024-04-19 05:59
> I talked with @smlambert , we will create a separate target for CryptoTest to trigger tests directly using jtreg, say `CryptoTests_jtreg`. `CryptoTests` will remain running with run.sh in CryptoTest repo. Once run.sh at CryptoTest is fully prepared for execution on all platforms, we can consolidate it into one target in the future if needed.
> 
> This is to avoid situations like [eclipse-openj9/openj9#19164 (comment)](https://github.com/eclipse-openj9/openj9/issues/19164#issuecomment-2064179534), where we lack access to the machine or the env.

That is good workaround, but please keep cryptotests_jtreg to run on the broken paltforms and vendors only. Keep all others tu run original target.

**Comment by judovana** [comment] 2024-04-19 15:46
Continuing https://github.com/adoptium/aqa-tests/pull/5248#pullrequestreview-2011754569 as advised.

Is it possible to make both CryptoTests and CryptoTests_jtreg  vendor neutral, and just split them on architecture?
That way The z/os solaris or whatever  had the failures would be happy, and similarly the redhat will not be running a uniq custom targets, which was never an intention.

**Comment by llxia** [comment] 2024-04-26 15:05
Close this issue as the problem is resolved.

**Closed by llxia** 2024-04-26 15:05 UTC

**Comment by judovana** [comment] 2024-04-26 15:38
The issue is just temporarily workarounded
