### ISSUE TITLE
jdk_util_1 FAILED in Test_openjdk21_hs_sanity.openjdk_x86-64_mac (java/util/BitSet/stream/BitSetStreamTest.java)

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4923] opened 2023-12-13 16:40 UTC
**Test Info**
Test Name: jdk_util_1
Test case: java/util/BitSet/stream/BitSetStreamTest.java
Test Duration: 18 min 51 sec
Machine: test-orka-macos14-x64-nhqhs
TRSS link for the test output: https://trss.adoptium.net/output/test?id=6572570620748f006f878edc

**Build Info**
Build Name: Test_openjdk21_hs_sanity.openjdk_x86-64_mac
Jenkins Build start time: Dec 07 2023, 08:14 am
Jenkins Build URL: https://ci.adoptium.net/job/Test_openjdk21_hs_sanity.openjdk_x86-64_mac/141/
TRSS link for the build: https://trss.adoptium.net/allTestsInfo?buildId=6572565420748f006f878e32

**Java Version**
openjdk version "21.0.1-beta" 2023-10-17
OpenJDK Runtime Environment Temurin-21.0.1+12-202312071249 (build 21.0.1-beta+12-202312071249)
OpenJDK 64-Bit Server VM Temurin-21.0.1+12-202312071249 (build 21.0.1-beta+12-202312071249, mixed mode)

[Rerun in Grinder](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=jdk_util_1&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_mac&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk21u&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk21u%2Fjdk21u-mac-x64-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=dev&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=67&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)

```
10:21:59  test BitSetStreamTest.testRandomStream(): failure
10:21:59  java.lang.AssertionError: expected [8162315] but found [7900171]
10:21:59  	at org.testng.Assert.fail(Assert.java:99)
10:21:59  	at org.testng.Assert.failNotEquals(Assert.java:1037)
10:21:59  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
10:21:59  	at org.testng.Assert.assertEquals(Assert.java:122)
10:21:59  	at org.testng.Assert.assertEquals(Assert.java:907)
10:21:59  	at org.testng.Assert.assertEquals(Assert.java:917)
10:21:59  	at BitSetStreamTest.testBitSetContents(BitSetStreamTest.java:238)
10:21:59  	at BitSetStreamTest.testRandomStream(BitSetStreamTest.java:228)
10:21:59  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
10:21:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
10:21:59  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
10:21:59  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
10:21:59  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
10:21:59  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
10:21:59  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
10:21:59  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
10:21:59  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
10:21:59  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
10:21:59  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
10:21:59  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
10:21:59  	at org.testng.TestRunner.run(TestRunner.java:585)
10:21:59  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
10:21:59  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
10:21:59  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
10:21:59  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
10:21:59  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
10:21:59  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
10:21:59  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
10:21:59  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
10:21:59  	at org.testng.TestNG.runSuites(TestNG.java:1069)
10:21:59  	at org.testng.TestNG.run(TestNG.java:1037)
10:21:59  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
10:21:59  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
10:21:59  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
10:21:59  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
10:21:59  	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
10:21:59  	at java.base/java.lang.Thread.run(Thread.java:1583)
10:21:59  
10:21:59  ===============================================
10:21:59  java/util/BitSet/stream/BitSetStreamTest.java
10:21:59  Total tests run: 133, Passes: 132, Failures: 1, Skips: 0
```

- appears intermittent

**Comment by sxa** [comment] 2024-01-11 14:05
Grinding with 10 iterations:
- https://ci.adoptium.net/job/Grinder/8449 on [macincloud-2](https://ci.adoptium.net/computer/test-macincloud-macos1201-x64-2) with [2023-12-10 build](https://github.com/adoptium/temurin21-binaries/releases/download/jdk21u-2023-12-10-17-15-beta/OpenJDK21U-jdk_x64_mac_hotspot_2023-12-10-17-15.tar.gz).
- https://ci.adoptium.net/job/Grinder/8450 on [macincloud-1](https://ci.adoptium.net/computer/test-macincloud-macos1201-x64-1) with [2024-01-07 build (latest)]: https://github.com/adoptium/temurin21-binaries/releases/download/jdk21u-2024-01-07-20-00-beta/OpenJDK21U-jdk_x64_mac_hotspot_2024-01-07-20-00.tar.gz
- Re-run of 8450 so it runs on an orka machine too: https://ci.adoptium.net/job/Grinder/8451

**Comment by sxa** [comment] 2024-01-12 14:20
Re-run passed every time. I'm going to close this for now on the basis that I've been unable to reproduce it so it is unlikely to be a machine issue. We can reopen if it's seen again.

**Closed by sxa** 2024-01-12 14:20 UTC
