### ISSUE TITLE
Investigate and add jcstress in system test group

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3546] opened 2022-04-08 18:35 UTC
We should investigate and add jcstress in the system test group:

https://github.com/openjdk/jcstress

**Comment by Mesbah-Alam** [comment] 2022-04-29 18:37
Download jcstress-latest.jar from https://builds.shipilev.net/jcstress locally on my Mac and was able to start the test by doing: `java -jar jcstress-latest.jar` - which is the simplest way of running these tests according to the [doc](https://github.com/openjdk/jcstress). 

However, when [I try to do the same](https://github.com/adoptium/aqa-tests/compare/master...Mesbah-Alam:add-jcstress?expand=1) on Jenkins, I get an error : 

```
Error: Invalid or corrupt jarfile /home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/system/jcstress/jcstress-latest.jar
```

(Grinder/23306). 

Checking the size of jcstress-latest.jar on Jenkins shows its only 8K : 

```
13:55:36  + du -h /home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/system/jcstress/jcstress-latest.jar
13:55:36  8.0K	/home/jenkins/workspace/Grinder/aqa-tests/TKG/../../jvmtest/system/jcstress/jcstress-latest.jar
```
(all-nodes-matching-labels/555). 

While the actual size of jcstress-latest.jar is 54.6 MiB (ref: https://builds.shipilev.net/jcstress). 

---- 

An alternative way to do this would be to checkout jcstress source and build it as part of systemtest.getDependency job - but that is a more complicated route. 

@llxia - would you be aware of any reasons why Jenkins may prevent download of jars from https://builds.shipilev.net/jcstress? (I had basically copied the `curl` command from [Dacapo](https://github.com/adoptium/aqa-tests/blob/9a25e28294e24e67db11bcaf83990dc6c48710f9/perf/dacapo/build.xml#L30).

**Comment by llxia** [comment] 2022-04-29 18:46
From what I can see, you are pointing https://builds.shipilev.net/jcstress, not a specific jar.
https://github.com/adoptium/aqa-tests/compare/master...Mesbah-Alam:add-jcstress?expand=1#diff-8a2f84603fb402a5feff98b12271e8a711baabf03d1efe2647ce1e3552bf629bR30

**Comment by Mesbah-Alam** [comment] 2022-04-29 19:09
Ah, right! Thanks! I got confused by the `curl` command from [Dacapo](https://github.com/adoptium/aqa-tests/blob/9a25e28294e24e67db11bcaf83990dc6c48710f9/perf/dacapo/build.xml#L30)).  

Got the test to work now: Grinder/23312!

**Comment by llxia** [comment] 2022-04-29 19:17
Thanks @Mesbah-Alam . 
For future enhancement, we should add the jar download into `systemtest.getDependency` job to avoid any download issue. This can be a separate issue.

**Comment by Mesbah-Alam** [comment] 2022-04-29 19:28
jcstress framework offers a nice option to run different flavours of the test: 

```
 -m <mode>                   Test mode preset: sanity, quick, default, tough, stress. 
```

Trying them all out together in a grinder to see how long each takes: Grinder/23316.

**Comment by smlambert** [comment] 2022-09-07 19:01
@jabrena @Mesbah-Alam - we can use this enhancement issue to discuss next steps...

There were a couple of questions in our Slack discussion:

- Running locally, the general steps outlined [here](https://github.com/eclipse-openj9/openj9/wiki/Reproducing-Test-Failures-Locally#general-steps).  One can also run tests using a Github workflow, I have an example where I have created a personal repository to use for testing and added a test.yml file that can trigger these tests... I believe we even support personal aqa-tests branches, but my personal fork is still off of the older named adoptopenjdk/openjdk-tests repo, so my branch fails to run.  You can see an example of running the `_jcstress_SampleTestBench` target from master branch [here](https://github.com/smlambert/protest/actions/runs/2996763989).

For any large/long-running jcstress test targets we may intend to add, we can add them to the new 'dev' level.  You can see an [example of a new target](https://github.com/smlambert/openjdk-tests/blob/jcstress1/system/jcstress/playlist.xml#L27-L37) I have added in my branch here.

While I am hitting a snag to run that as a github workflow due to my forked repository name, this is an example of a newly added target my branch running in Jenkins in this [Grinder/5676 run](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/5676/).

- How to decide what new jcstress tests to add, knowing that the typical run can take hours/days.  Does it make sense to selectively choose some of the tests in [test_custom](https://github.com/openjdk/jcstress/tree/master/tests-custom/src/main/java/org/openjdk/jcstress/tests) and run them?  Noting that the [pre-integration.yml](https://github.com/openjdk/jcstress/blob/master/.github/workflows/pre-integration.yml#L44) file in the jcstress repo runs a single test (UnfencedDekker), which is the additional testcase I have added in my branch for another example, over and above the SampleTestBench example that Mesbah already added..

**Comment by jabrena** [comment] 2022-09-09 13:39
Hi, 

I am going to begin the process from Scratch. Reading the documentation to run in local the project.

- [ ] https://github.com/eclipse-openj9/openj9/wiki/Reproducing-Test-Failures-Locally#general-steps
- [ ] https://github.com/adoptium/aqa-tests/blob/master/doc/Prerequisites.md

**Comment by jabrena** [comment] 2022-09-13 22:32
Added all test from the folder custom_test in the PR: https://github.com/adoptium/aqa-tests/pull/3961

**Comment by jabrena** [comment] 2022-09-14 06:22
Hi @Mesbah-Alam, you mentioned in previous comments in this issue some configuration parameters for jcstress tests. 

Where is located the configuration for jcstress?

**Comment by Mesbah-Alam** [comment] 2022-09-14 13:54
Hi @jabrena , 

I had mentioned about jcstress input arguments like `-m` above, were you looking for those? 

The full list of options can be found by running the jcstress jar with `--h` option : 

```
 java -jar jcstress-latest.jar --h   
Java Concurrency Stress Tests
---------------------------------------------------------------------------------
Rev: 0fdc513466a87a22, built by buildbot with 17.0.1 at 2022-04-14T21:11:05Z

Usage: java -jar jcstress.jar [options]
 [opt] means optional argument.
 <opt> means required argument.
 "+" means comma-separated list of values.
 "time" arguments accept time suffixes, like "100ms".

  [arguments]                 

  -af [mode]                  Use the specific affinity mode, if available. 

  -c <N>                      Number of CPUs to use. Defaults to all CPUs in the system. 
                              Reducing the number of CPUs limits the amount of resources 
                              (including memory) the run is using. 

  -f [count]                  Should fork each test N times. "0" to run in the embedded mode 
                              with occasional forking. 

  -fsm [multiplier]           Fork multiplier for randomized/stress tests. This allows 
                              more efficient randomized testing, as each fork would use a 
                              different seed. 

  -h                          Print this help. 

  -hs <MB>                    Java heap size per fork, in megabytes. This affects the 
                              stride size: maximum footprint will never be exceeded, 
                              regardless of min/max stride sizes. 

  -iters <N>                  Iterations per test. 

  -jvmArgs <string>           Use given JVM arguments. This disables JVM flags 
                              auto-detection, and runs only the single JVM mode. Either a 
                              single space-separated option line, or multiple options 
                              are accepted. This option only affects forked runs. 

  -jvmArgsPrepend <string>    Prepend given JVM arguments to auto-detected 
                              configurations. Either a single space-separated option 
                              line, or multiple options are accepted. This option only 
                              affects forked runs. 

  -l [bool]                   List the available tests matching the requested settings. 

  -m <mode>                   Test mode preset: sanity, quick, default, tough, stress. 

  -p <result file>            Re-run parser on the result file. This will not run any 
                              tests. 

  -r <dir>                    Target destination to put the report into. 

  -sc [bool]                  Use split per-actor compilation mode, if available. 

  -spinStyle <style>          Busy loop wait style. HARD = hard busy loop; THREAD_YIELD = 
                              use Thread.yield(); THREAD_SPIN_WAIT = use 
                              Thread.onSpinWait(); LOCKSUPPORT_PARK_NANOS = use 
                              LockSupport.parkNanos(). 

  -strideCount <N>            Internal stride count per epoch. Larger value increases 
                              cache footprint. 

  -strideSize <N>             Internal stride size. Larger value decreases the 
                              synchronization overhead, but also reduces the number of 
                              collisions. 

  -t <regexp>                 Regexp selector for tests. 

  -time <ms>                  Time to spend in single test iteration. Larger value 
                              improves test reliability, since schedulers do better job 
                              in the long run. 

  -v                          Be verbose. 

  -vv                         Be extra verbose. 

  -vvv                        Be extra extra verbose. 

```

**Comment by smlambert** [comment] 2022-09-14 16:37
$(JVM_OPTIONS) are configurable through various methods

We do not currently pass in separate arguments, but I think we could... some suggestion here: https://github.com/adoptium/aqa-tests/pull/3961#issuecomment-1247009274

I think we should make it even "more generic" and applicable to other types of testing and frameworks.  Call it FRAMEWORK_OPTIONS or APPLICATION_OPTIONS, and when that environment variable pass it to the framework or application.     

FYI @llxia 

This would allow us to not bloat the Jenkins parameter list, but reuse APPLICATION_OPTIONS for the following use cases:
- openjdk tests: eventual replacement of [JTREG_BASIC_OPTIONS](https://github.com/adoptium/aqa-tests/blob/master/openjdk/openjdk.mk#L68) and [EXTRA_JTREG_OPTIONS](https://github.com/adoptium/aqa-tests/blob/master/openjdk/openjdk.mk#L66)
- jck tests: passing arguments to javatest directly, currently done via [OTHER_OPTS](https://github.com/adoptium/aqa-tests/blob/master/jck/jck.mk#L68)
- external tests: passing arguments into [external.sh](https://github.com/adoptium/aqa-tests/blob/master/external/external.sh#L62) 
- perf tests: passing optional args to [perf benchmarks](https://github.com/adoptium/aqa-tests/tree/master/perf)

**Comment by jabrena** [comment] 2022-10-04 09:54
What is the next step?

**Comment by smlambert** [comment] 2022-10-04 12:29
Next step is that we will create a job that runs these targets weekly and monitor them.  

I also see in one of the Grinders that jcstress_StampedLockPairwiseTests target takes 176 minutes to run (seems to be one of the longest running targets).  I was going observe the execution time of that target in particular across all the platforms to see if we need to consider disabling it for practical reasons.  

Ideally we would also gather information regarding why and when these tests are helpful, and if there would be any good reasons to trigger these tests on certain PRs versus others.

**Comment by jabrena** [comment] 2022-10-04 13:33
Oki, what pipeline do you recommend to copy and adapt for that purpose?

**Comment by smlambert** [comment] 2022-10-04 16:37
I am running it via the AQA_Test_Pipeline job, which is a job that can launch and run any test target on any platform and is also being monitored by [TRSS](https://trss.adoptium.net/builds?buildName=AQA_Test_Pipeline&url=https%3A%2F%2Fci.adoptopenjdk.net&type=Test)
 
Today I have launched https://ci.adoptopenjdk.net/job/AQA_Test_Pipeline/92/ - I launch other runs on other platforms on a weekly schedule so we can monitor over the next few weeks.  

I believe that we can close this issue now (and open a new one as we see the need to modify/enhance this suite).

**Closed** 2022-10-04 16:47 UTC
Labels: type:system
