### ISSUE TITLE
make compile on Mauve tests requires java in path

### ISSUE THREAD

**Issue by sxa** [adoptium/aqa-tests#2387] opened 2021-03-16 11:44 UTC
**Describe the bug** Building the mauve suites requires a java explicitly in the `PATH`

**To Reproduce**
Steps to reproduce the behavior (or Grinder rerun link): `BUILD_LIST=system make compile`
```
get-source:

BUILD FAILED
/home/sxa/openjdk-tests/TKG/scripts/build_test.xml:76: The following error occurred while executing this line:
/home/sxa/openjdk-tests/system/common.xml:255: The following error occurred while executing this line:
/home/sxa/openjdk-tests/system/common.xml:246: The following error occurred while executing this line:
/home/sxa/openjdk-tests/system/openjdk-systemtest/openjdk.build/build.xml:58: The following error occurred while executing this line:
/home/sxa/openjdk-tests/system/openjdk-systemtest/openjdk.test.mauve/build.xml:363: Execute failed: java.io.IOException: Cannot run program "java" (in directory "/tmp/mauve"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
```

**Expected behavior** Test suite would be able to use the java from `TEST_JDK_HOME` but it doesn't.

**Screenshots** n/a

**Additional context** n/a

I suspect this would be fairly simple to change, and I can't see a reason why it would be beneficial to use the system one instead of the one under test for building, so I would suggest that this be changed to invoke `TEST_JDK_HOME/bin/java` (or `jre/bin/java`) instead of relying on the PATH for simplicity.

**Comment by sxa** [comment] 2021-03-16 12:01
(Potential good first issue?)

**Comment by SAY-droid427** [comment] 2021-04-13 09:21
Hi @smlambert! Can this issue be assigned to me as an Outreachy applicant?

**Comment by smlambert** [comment] 2021-04-13 19:32
For sure @SAY-droid427 !

**Comment by SAY-droid427** [comment] 2021-04-14 14:47
Hi @smlambert! Thanks for assigning the issue to me. Could you please explain the steps I should follow to solve this issue? Thank you!

**Comment by smlambert** [comment] 2021-04-14 19:36
Hi @SAY-droid427 - a few things you can do to start with: 

- try to reproduce this failure locally (by checking you have no java in your PATH environment variable and then loosely following these [general steps](https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally#general-steps) with setting BUILD_LIST=system and  TEST_JDK_HOME to something you have installed from adoptopenjdk.net, and test target you attempt to run is _MauveSingleThrdLoad_HS_5m.  See if you get the same problem as reported in this issue (presumably so).  
- look at the file and line number identified in the description, to understand more about the failure

```
get-source:

BUILD FAILED
/home/sxa/openjdk-tests/TKG/scripts/build_test.xml:76: The following error occurred while executing this line:
/home/sxa/openjdk-tests/system/common.xml:255: The following error occurred while executing this line:
/home/sxa/openjdk-tests/system/common.xml:246: The following error occurred while executing this line:
/home/sxa/openjdk-tests/system/openjdk-systemtest/openjdk.build/build.xml:58: The following error occurred while executing this line:
/home/sxa/openjdk-tests/system/openjdk-systemtest/openjdk.test.mauve/build.xml:363: Execute failed: java.io.IOException: Cannot run program "java" (in directory "/tmp/mauve"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
```

Some notes:
These xml files are ant scripts (see more about ant in this [ant tutorial)](https://ant.apache.org/manual/tutorial-HelloWorldWithAnt.html), looking at each:

- [system/openjdk-systemtest/openjdk.test.mauve/build.xml:363](https://github.com/adoptium/aqa-systemtest/blob/master/openjdk.test.mauve/build.xml#L363) - instruction that says use an executable named java (and does not define 'which' java to use, so ant will attempt to use the one on the PATH... 

so it may be at this line that can be changed so that if Java is not on the PATH, try to use the Java defined at TEST_JDK_HOME which should be set if people are using the preferred method for running systemtest material (via TKG/openjdk-tests)

**Comment by SAY-droid427** [comment] 2021-04-15 12:43
@smlambert Thank you so much for the detailed explanation! I will try to reproduce the bug locally and reach out to you for help if I get stuck. Would you suggest that I take a short video tutorial on Apache ant for better understanding of the project or is the tutorial you have mentioned enough?

**Comment by smlambert** [comment] 2021-04-15 18:29
Ant is used to compile java test material in our project.  Make/gmake used for compiling native test material.  Having basic understanding of how things are built is useful, but running things directly and trying to make changes is like more useful for understanding.

**Comment by SAY-droid427** [comment] 2021-04-18 13:22
@smlambert I am a bit stuck while installing the pre-reqs on my new laptop(using Linux). I have checked that  I have no java in my PATH environment variable. I have installed Apache-ant 1.10.5 version using apt and also downloaded the ant-contrib1.05b. The ant has been downloaded to the usr/bin/ant. But how do I link the ant-contrib? I had been following these steps :[http://ant-contrib.sourceforge.net/](http://ant-contrib.sourceforge.net/). I have installed all other pre-reqs.  And also, for this issue, should I set my PATH environment variable for JAVA? A little guidance would put me in the right track. Thanks!

**Comment by smlambert** [comment] 2021-04-18 14:04
For installing ant-contrib, I believe its just a matter of putting the ant-contrib-1.05b.jar file in the lib directory of your ant installation.  

Alternatively, if you are on Ubuntu 18.04, perhaps you can try to use the same steps used to set up a ubuntu based test container? https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/docker/Dockerfile#L36-L39 

For this issue, to recreate the problem that is reported, you would not set any installed Java or OpenJDK binaries on your PATH.  The problem we are trying to address is to have the mauve ant scripts use the java executable at TEST_JDK_HOME (as sometimes there will not be one defined on the path).

**Comment by SAY-droid427** [comment] 2021-04-18 14:44
> For installing ant-contrib, I believe its just a matter of putting the ant-contrib-1.05b.jar file in the lib directory of your ant installation.
> 
> Alternatively, if you are on Ubuntu 18.04, perhaps you can try to use the same steps used to set up a ubuntu based test container? https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/docker/Dockerfile#L36-L39
> 
> For this issue, to recreate the problem that is reported, you would not set any installed Java or OpenJDK binaries on your PATH. The problem we are trying to address is to have the mauve ant scripts use the java executable at TEST_JDK_HOME (as sometimes there will not be one defined on the path).

Yes, I had understood that but the problem is I am unable to find the ant directory. I have run the command `which ant` and found that it is in `/usr/bin/ant`. But when I moved to the location I donot find any folder containing lib directory.

**Comment by smlambert** [comment] 2021-04-18 18:30
Perhaps then try the alternate approach of using apt-get update && install for ant and ant-contrib
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/docker/Dockerfile#L39 ?

**Comment by SAY-droid427** [comment] 2021-04-19 02:24
> Perhaps then try the alternate approach of using apt-get update && install for ant and ant-contrib
> https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/docker/Dockerfile#L39 ?

Yes I will get this to work! Thank you for the help!

**Comment by SAY-droid427** [comment] 2021-04-19 14:03
> @smlambert I am a bit stuck while installing the pre-reqs on my new laptop(using Ubuntu 18.04). I have checked that I have no java in my PATH environment variable. I have installed Apache-ant 1.10.5 version using apt and also downloaded the ant-contrib1.05b. The ant has been downloaded to the usr/bin/ant. But how do I link the ant-contrib? I had been following these steps :http://ant-contrib.sourceforge.net/.I got a bit confused reading this. I have installed all other pre-reqs for the issue. And also, for this issue, should I set my PATH environment variable for JAVA, because I have installed OpenJDK11? A little guidance would put me in the right track. Thanks!

I have solved this issue,  by re-installing ant manually. I will run the tests locally now and continue the work on this issue! Thank you

**Comment by smlambert** [comment] 2021-04-19 17:40
Great to hear @SAY-droid427, thanks for persevering !

**Comment by SAY-droid427** [comment] 2021-04-22 12:45
Hi @smlambert 
On executing the `make_compile` command in my terminal, I faced this issue.
`JAVA_HOME is set to /usr/lib/jvm/java-11-openjdk-amd64/bin/java
rm -f -r /home/sayani/Desktop/openjdk-tests/TKG/../TKG/output_compilation; \
mkdir -p /home/sayani/Desktop/openjdk-tests/TKG/../TKG/output_compilation; \
(ant -f ./scripts/build_tools.xml -DTEST_JDK_HOME=/usr/lib/jvm/java-11-openjdk-amd64/bin/java -DTEST_ROOT=/home/sayani/Desktop/openjdk-tests/TKG/.. 2>&1; echo $? ) | tee "/home/sayani/Desktop/openjdk-tests/TKG/../TKG/output_compilation/compilation.log"; \
if [ -z "$(tail -1 /home/sayani/Desktop/openjdk-tests/TKG/../TKG/output_compilation/compilation.log | grep 0)" ]; then perl scripts/moveDmp.pl --compileLogPath="/home/sayani/Desktop/openjdk-tests/TKG/../TKG/output_compilation/compilation.log" --testRoot="/home/sayani/Desktop/openjdk-tests/TKG/.."; false; else rm -f -r "/home/sayani/Desktop/openjdk-tests/TKG/../TKG/output_compilation"; fi
We cannot run Java, please ensure you have Java installed.
  We have tried to execute /usr/lib/jvm/java-11-openjdk-amd64/bin/java/bin/java but failed.
If you have installed Java in a unusual place you can set JAVA_HOME
to the directory containing the Java installation.
1
makefile:75: recipe for target 'compileTools' failed
make: *** [compileTools] Error 1
`
On executing `java -version`, I received the following output:
`openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)
`
As mentioned in this issue, I had removed JAVA from my PATH environment variable.
Could you please help me with this?

**Comment by smlambert** [comment] 2021-04-22 18:22
no, not quite the same error.

As @sxa reports in the issue description, he sees `Cannot run program "java" (in directory "/tmp/mauve"): error=2, No such file or directory` 

Presumably in his environment, there is no java on the PATH.  In your environment, there must be, or you would not be able to type java -version and get version output.  (and since your error says there is no javac, guessing its a version of java that does not contain the javac compiler ...).

If you run 'which java' what is the output, and then when you run 'printenv' do you see that output in the PATH variable?

**Comment by SAY-droid427** [comment] 2021-04-23 02:20
Output of printenv:
```
CLUTTER_IM_MODULE=xim
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_MENU_PREFIX=gnome-
LANG=en_IN
DISPLAY=:0
GNOME_SHELL_SESSION_MODE=ubuntu
COLORTERM=truecolor
USERNAME=sayani
XDG_VTNR=2
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
XDG_SESSION_ID=2
USER=sayani
DESKTOP_SESSION=ubuntu
QT4_IM_MODULE=xim
TEXTDOMAINDIR=/usr/share/locale/
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/c2d44dc2_68ed_489b_abe7_c86982354bbd
PWD=/home/sayani
HOME=/home/sayani
TEXTDOMAIN=im-config
SSH_AGENT_PID=2068
QT_ACCESSIBILITY=1
XDG_SESSION_TYPE=x11
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop
XDG_SESSION_DESKTOP=ubuntu
GJS_DEBUG_OUTPUT=stderr
GTK_MODULES=gail:atk-bridge
WINDOWPATH=2
TERM=xterm-256color
SHELL=/bin/bash
VTE_VERSION=5202
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
IM_CONFIG_PHASE=2
XDG_CURRENT_DESKTOP=ubuntu:GNOME
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
GNOME_TERMINAL_SERVICE=:1.70
XDG_SEAT=seat0
SHLVL=1
LANGUAGE=en_IN:en
GDMSESSION=ubuntu
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LOGNAME=sayani
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_RUNTIME_DIR=/run/user/1000
XAUTHORITY=/run/user/1000/gdm/Xauthority
ANT_HOME=/usr/local/ant
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
PATH=/usr/local/ant/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/ant/bin
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
SESSION_MANAGER=local/sayani-VivoBook-ASUSLaptop-X512FL-X512FL:@/tmp/.ICE-unix/1967,unix/sayani-VivoBook-ASUSLaptop-X512FL-X512FL:/tmp/.ICE-unix/1967
LESSOPEN=| /usr/bin/lesspipe %s
GTK_IM_MODULE=ibus
_=/usr/bin/printenv

```

Output of `which java`:
```
/usr/bin/java

```
Executing echo $JAVA_HOME gives a blank line.
Executing echo $PATH gives:
```
/usr/local/ant/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/ant/bin

```

I did not explicitly install OpenJDK11 because Ubuntu18.04 has pre-installed OpenJDK11.

**Comment by SAY-droid427** [comment] 2021-04-24 06:46
@smlambert  I donot have JAVA_HOME set as can be seen:
![JA](https://user-images.githubusercontent.com/59281636/115949995-300cfe00-a4f6-11eb-8e19-adb43bc2b4b9.png)

However I can successfully run the mauve tests. I donot get any errors while running `make compile` or `make  _MauveSingleThrdLoad_HS_5m`.
![make_k](https://user-images.githubusercontent.com/59281636/115950087-cc370500-a4f6-11eb-9d74-145825ac7c9e.png)
![mak](https://user-images.githubusercontent.com/59281636/115950094-d9ec8a80-a4f6-11eb-9c00-c26eb7e6aa44.png)

**Comment by SAY-droid427** [comment] 2021-04-27 02:57
> Hi @smlambert
> On executing the `make_compile` and ` make _MauveSingleThrdLoad_HS_5m` command in my terminal, I faced this issue.
> ![ERRORS](https://user-images.githubusercontent.com/59281636/115721847-0b9d0e80-a39c-11eb-81f9-0008c569d54b.png)
> 
> On executing `java -version`, I received the following output:
> 
> ```
> openjdk version "11.0.7" 2020-04-14
> OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
> OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)
> ```
> 
> As mentioned in this issue, I had removed JAVA from my PATH environment variable.
> Is this the error we sought to remove?

@smlambert Please take a look at this

**Comment by smlambert** [comment] 2021-04-27 15:05
Hmm, wondering if this issue has already been addressed via some other pull request.

Looking for input from @sxa as he raised the issue and from @Mesbah-Alam as he is familiar with mauve tests and how they are built...  Can either of you make suggestions to @SAY-droid427 to progress this investigation?

**Comment by Mesbah-Alam** [comment] 2021-04-27 15:17
Looking at the [last](https://github.com/AdoptOpenJDK/openjdk-tests/issues/2387#issuecomment-827276792) screen shot above, it looks like the first issue was caused by `javac` compiler not running properly. 

@SAY-droid427 - Could you please ensure the JDK you are using contains the `javac` executable? (i.o.w, that you are using a JDK and not merely a JRE?).

**Comment by SAY-droid427** [comment] 2021-04-27 16:30
> Looking at the [last](https://github.com/AdoptOpenJDK/openjdk-tests/issues/2387#issuecomment-827276792) screen shot above, it looks like the first issue was caused by `javac` compiler not running properly.
> 
> @SAY-droid427 - Could you please ensure the JDK you are using contains the `javac` executable? (i.o.w, that you are using a JDK and not merely a JRE?).

I am so sorry, I had quoted the wrong reply @Mesbah-Alam .The javac problem was solved.

**Comment by SAY-droid427** [comment] 2021-04-27 16:32
> @smlambert I donot have JAVA_HOME set as can be seen and JAVA is not present in the PATH environment variable:
> ![JA](https://user-images.githubusercontent.com/59281636/115949995-300cfe00-a4f6-11eb-8e19-adb43bc2b4b9.png)
> 
> ![PA](https://user-images.githubusercontent.com/59281636/115950209-947c8d00-a4f7-11eb-9cb0-eb70c44dda5e.png)
> 
> However I can run the mauve tests. I donot get any errors while running `make compile` or `make _MauveSingleThrdLoad_HS_5m`.
> 
> ![make_k](https://user-images.githubusercontent.com/59281636/115950087-cc370500-a4f6-11eb-9d74-145825ac7c9e.png)
> ![mak](https://user-images.githubusercontent.com/59281636/115950094-d9ec8a80-a4f6-11eb-9c00-c26eb7e6aa44.png)
> 
> However it says SKIPPED=2 tests due to jvm.

@Mesbah-Alam I have been able to successfully run the mauve tests on my Ubuntu machine( I think from the [screenshots](https://github.com/AdoptOpenJDK/openjdk-tests/issues/2387#issuecomment-826045250) attached). But according to the issue I shouldn't be able to run the test successfully.

**Comment by Mesbah-Alam** [comment] 2021-04-27 16:53
@SAY-droid427 - you seem to be running the Mauve tests using the TKG layer, in which case TKG would have been taking care of determining which Java to use to compile the test. 

@sxa - Could you please confirm that you were _NOT_ running the Mauve tests using TKG, and instead were using the [systemtest make layer](https://github.com/adoptium/aqa-systemtest/blob/master/openjdk.build/makefile), when you had faced the original issue?

**Comment by SAY-droid427** [comment] 2021-04-28 02:46
@Mesbah-Alam I had been using [these](https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally#general-steps) general instructions while running the Mauve tests and I think it was using the TKG layer. Could you please tell me how do I use the systemtest make layer? I will start working on it asap! Thank you!

**Comment by Mesbah-Alam** [comment] 2021-04-28 02:56
@SAY-droid427 : please follow the instructions here: https://github.com/adoptium/aqa-systemtest

**Comment by SAY-droid427** [comment] 2021-04-28 03:34
![d](https://user-images.githubusercontent.com/59281636/116341470-9f3c6800-a7fe-11eb-9037-ac89a32c5507.png)

@Mesbah-Alam I guess these  are the steps you asked me to follow? In the 7th instruction, should I run 
`make  _MauveSingleThrdLoad_HS_5m` instead of `make test` in the `aqa-systemtest/openjdk.build` in place of `openjdk-systemtest/openjdk.build`?

**Comment by Mesbah-Alam** [comment] 2021-04-28 12:50
> In the 7th instruction, should I run
make _MauveSingleThrdLoad_HS_5m instead of make test in the aqa-systemtest/openjdk.build in place of openjdk-systemtest/openjdk.build?

`test.MauveSingleThreadLoadTest_5m` needs to be run (The associated target is defined [here](https://github.com/adoptium/aqa-systemtest/blob/master/openjdk.build/makefile#L863)). 

> makefile:108: *** ERROR: JAVA_HOME not set.  Stop.

I guess this is the original problem that this issue is trying to resolve, @sxa  ?

**Comment by SAY-droid427** [comment] 2021-04-28 13:07
> > In the 7th instruction, should I run
> > make _MauveSingleThrdLoad_HS_5m instead of make test in the aqa-systemtest/openjdk.build in place of openjdk-systemtest/openjdk.build?
> 
> `test.MauveSingleThreadLoadTest_5m` needs to be run (The associated target is defined [here](https://github.com/adoptium/aqa-systemtest/blob/master/openjdk.build/makefile#L863)).
> 
> > makefile:108: *** ERROR: JAVA_HOME not set.  Stop.
> 
> I guess this is the original problem that this issue is trying to resolve, @sxa ?

I presumed that I had to set the BUILD_LIST=system and TEST_JDK_HOME explicitly for this issue like [this](https://github.com/AdoptOpenJDK/openjdk-tests/issues/2387#issuecomment-819780727)

**Comment by smlambert** [comment] 2021-04-28 18:35
This is the (annoying) problem of having two make layers and being stuck with supporting both.  I had not realized that the issue raised in this openjdk-tests repo was referring to an issue regarding running the systemtest make layer, so I had originally misdirected you @SAY-droid427.  

The systemtest make layer does not know anything about a TEST_JDK_HOME (nor does it ever really need to).  What @sxa suggests is that _if_ JAVA_HOME is not set, then tell they systemtest make layer to check for whether TEST_JDK_HOME is set, and if it is, use it.

**Comment by SAY-droid427** [comment] 2021-04-30 04:23
> This is the (annoying) problem of having two make layers and being stuck with supporting both. I had not realized that the issue raised in this openjdk-tests repo was referring to an issue regarding running the systemtest make layer, so I had originally misdirected you @SAY-droid427.
> 
> The systemtest make layer does not know anything about a TEST_JDK_HOME (nor does it ever really need to). What @sxa suggests is that _if_ JAVA_HOME is not set, then tell they systemtest make layer to check for whether TEST_JDK_HOME is set, and if it is, use it.

Yes, I understood the task. I was a bit confused about the two layers, but now it is clear that there are two layers: TKG and systemtest layer. While running in the TKG layer, the mauve tests run successfully, however while running via the systemtest layer, if JAVA_HOME is not set, then we have to check whether the TEST_JDK_HOME is set and if it is set, then we should use it and run the tests successfully. I was a bit confused because I am not getting the exact error output as @sxa was getting. Now the question is how to check whether JAVA_HOME is set or not and if not, then check for TEST_JDK_HOME and if that is set, how to use it. I will try to gain some more knowledge about this and send a draft PR in a day. Thank you @smlambert @Mesbah-Alam for so much of help in this issue.

**Comment by smlambert** [comment] 2022-10-09 15:20
Closing as won't fix, as we will move more and more away from running systemtest material independently from TKG (hopefully to the point where we can remove the extra make layer and technical debt that accumulates by having 2 layers to support).

**Closed by smlambert** 2022-10-09 15:20 UTC
Labels: bug, good first issue
